package:
    name: python-twitter
    version: {{ environ.get('GIT_DESCRIBE_TAG','')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
    git_url: https://github.com/bear/python-twitter.git
    git_rev: master

  # use a local url and leave rev blank to have conda build current head, currently
  # requires master branch of conda-build to work
  # git_rev: ?

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
    build:
      - python
      - setuptools
      - requests
      - requests-oauthlib
  
    run:
      - python
      - requests
      - requests-oauthlib

test:
  # Python imports
  imports:
    - twitter

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bear/python-twitter
  license: Apache License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
